apiVersion: batch/v1
kind: Job
metadata:
  name: stress
spec:
  template:
    spec:
      containers:
      - name: stress
        image: progrium/stress
        args: [--cpu 2", "--io 1", "--vm 2", "--vm-bytes 128M", "--timeout 10s"]
        terminationMessagePolicy: FallbackToLogsOnError
      restartPolicy: Never
  backoffLimit: 4
